#
# Configure the server
#
server:
  port: 8080
  servlet:
    context-path: /hr
  shutdown: graceful
#
# Spring Configuration
#
spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/ORCLPDB1
    username: hr
    password: super-secret-password
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
      poolName: SpringHr
  liquibase:
    changeLog: classpath:db/changelog.oracle.xml

#
# Actuator
#
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    info:
      enabled: true

#
# Swagger
#
springdoc:
  api-docs:
    path: /openapi
  swagger-ui:
    path: /swagger
    # disable petstore
    disable-swagger-default-url: true